#!/usr/bin/env bash
# Install nginx web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i 's/server_name _;/&\n	location \/redirect_me {\n	    return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n	}/' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i 's@server_name _;@&\n    error_page 404 /404.html;\n    location = /404.html {\n        root /var/www/html;\n        internal;\n    }@' /etc/nginx/sites-available/default
sed -i "s@location / {@&\n		add_header X-Served-By $(hostname);@" /etc/nginx/sites-available/default
service nginx start 
