#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "frontend http
	bind *:80
	mode http
	default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
	balance roundrobin
	server web-01 34.205.65.92:80 check
	server web-02 52.205.76.119:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
