#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i 's/server_name _;/&\n	listen 8080;/' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
