#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
service nginx restart
